### ISSUE TITLE
Example program `display` not working

### ISSUE THREAD

**Issue by glennib** [lulf/microbit-bsp#2]
Hello,

Thank you for this crate, it looks promising. I really want to get into embassy for the Microbit.

I just purchased a Microbit v2, and want to try out the `display` example program, but can't seem to get it to work. I added an additional print to confirm that the program actually started:

```patch
diff --git a/examples/display/src/main.rs b/examples/display/src/main.rs
index e41efc8..427a81b 100644
--- a/examples/display/src/main.rs
+++ b/examples/display/src/main.rs
@@ -15,6 +15,8 @@ async fn main(_spawner: Spawner) {
     let mut btn_a = board.btn_a;
     let mut btn_b = board.btn_b;
 
+    defmt::info!("Started!");
+
     display.set_brightness(display::Brightness::MAX);
     display.scroll("Hello, World!").await;
     defmt::info!("Application started, press buttons!");
```

The program seems to start, this is the terminal output:
```
$ cargo run --release
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/glenn/src/microbit-bsp/examples/display/Cargo.toml
workspace: /home/glenn/src/microbit-bsp/examples/Cargo.toml
    Finished release [optimized] target(s) in 0.04s
     Running `probe-run --chip nRF52833_xxAA /home/glenn/src/microbit-bsp/examples/target/thumbv7em-none-eabihf/release/microbit-async-display-example`
(HOST) INFO  flashing program (5 pages / 20.00 KiB)
(HOST) INFO  success!
(HOST) WARN  insufficient DWARF info; compile your program with `debug = 2` to enable location info
(HOST) WARN  `defmt::timestamp!` implementation was found, but timestamp is not part of the log format; consider adding the timestamp `{t}` argument to the log format
────────────────────────────────────────────────────────────────────────────────
INFO  Started!
└─ <mod path> @ <file>:0
```

In addition, only two of the LEDs light up, and they are static. See the picture below. The board does not react to any button presses.

![P_20240117_213213](https://github.com/lulf/microbit-bsp/assets/3914032/2c26bd61-66b6-4baa-93eb-da2109726103)

I have confirmed that the buttons and other LEDs are working through another program (based on the example found [here](https://docs.rust-embedded.org/discovery/microbit/05-led-roulette/light-it-up.html)).

I can also show you a simpler test program using `microbit-bsp` that didn't work as expected:

```rust
#![no_std]
#![no_main]

use embassy_executor::Spawner;
use microbit_bsp::Microbit;
use {defmt_rtt as _, panic_probe as _};

#[embassy_executor::main]
async fn main(#[allow(clippy::used_underscore_binding)] _spawner: Spawner) {
    let board = Microbit::default();
    defmt::info!("Application started!");

    let mut btn_a = board.btn_a;

    loop {
        defmt::info!("Wait for any edge");
        btn_a.wait_for_any_edge().await;
        defmt::info!("There...");
    }
}
```

Which gives the following output, even though I am pressing both the buttons:

```
0.000091 INFO  Application started!
└─ test_embassy::____embassy_main_task::{async_fn#0} @ src/main.rs:17  
0.000213 INFO  Wait for any edge
└─ test_embassy::____embassy_main_task::{async_fn#0} @ src/main.rs:24 
```

No print of `There...`.

Do you have any idea of what can be wrong here?
Something about the executor not set up correctly?
Or should I configure the buttons?

I appreciate your work.

**Comment by glennib** [comment]
Here is an even simpler program that doesn't do what we expect:

```rust
#![no_std]
#![no_main]

use embassy_executor::Spawner;
use embassy_time::Timer;
use microbit_bsp::Microbit;
use {defmt_rtt as _, panic_probe as _};

#[embassy_executor::main]
async fn main(#[allow(clippy::used_underscore_binding)] _spawner: Spawner) {
    let _board = Microbit::default();
    defmt::info!("Application started!");
    Timer::after_millis(100).await;
    defmt::info!("Timer completed!");
    loop {
    }
}
```

Output:

```
0.000000 INFO  Application started!
└─ test_embassy::____embassy_main_task::{async_fn#0} @ src/main.rs:12
```

So is there maybe something about the executor or timer that needs setup?

**Comment by lulf** [comment]
@glennib Thanks for the great bug report. Indeed there was a bug (reproduced what you were seeing) after the latest update where there was a missing feature 'rt' on the embassy-nrf crate. I've pushed a fix and released a new version to crates.io now. Let me know if that works for you.

**Comment by glennib** [comment]
Thank you for the quick resolution! It does indeed seem to have fixed the issue.

https://github.com/lulf/microbit-bsp/assets/3914032/0e78c682-69bd-471a-83f1-63f9e4984037

Awesome :)
