### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by winksaville** [lulf/microbit-bsp#5]
I have a question I'd like to ask, using an issue is overkill so I'd like to suggest you enable [Discussions here on GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) for this repo or maybe use Discord or ...

**Comment by lulf** [comment]
@winksaville Done!
